import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import AuthButtons from "@/components/AuthButtons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Codev</title>
        <meta name="description" content="Generated by Codev" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-background min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 flex flex-col items-center justify-center p-4 gap-4">
          <Card className="w-full max-w-md">
            <CardHeader>
              <CardTitle>Welcome to the Authentication Demo</CardTitle>
              <CardDescription>Secure Email & Password Authentication</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="mb-4">This app demonstrates a secure authentication system with a clean, user-friendly interface.</p>
              <Button className="w-full" onClick={() => window.scrollTo({ top: document.getElementById('auth-section')?.offsetTop, behavior: 'smooth' })}>Get Started</Button>
            </CardContent>
          </Card>
          
          <div id="auth-section" className="w-full flex justify-center">
            <AuthButtons />
          </div>
        </main>
      </div>
    </>
  );
}
